name: Build Base Images

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './images'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build test image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/test:do_not_use -f Dockerfile-alpine .
          docker push ghcr.io/cfpb/regtech/sbl/test:do_not_use

      - name: 'Build alpine image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/alpine:3.18_${{github.run_attempt}} -f Dockerfile-alpine .

      - name: 'Build python-alpine image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/python-alpine:3.12_${{github.run_attempt}} -f Dockerfile-python-alpine .

      - name: 'Build nginx-alpine image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/nginx-alpine:1.27_${{github.run_attempt}} -f Dockerfile-nginx-alpine .

      - name: 'Build node-js-alpine image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/node-js-alpine:3.20_${{github.run_attempt}} -f Dockerfile-node-js-alpine .

      - name: 'Build python-ubi8 image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/python-ubi8:3.12_${{github.run_attempt}} -f Dockerfile-python-ubi8 .

# Github api reference only.
# We would need to use a dedicted user PAT since auto-generated GITHUB_TOKEN is not org admin which is required for delete 

#      - name: 'Delete test package'
#        run: |
#          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/cfpb/packages/container/regtech%2Fsbl%2Ftest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
