name: data-points-json-to-csv
on:
  push:
    branches-ignore:
      - main
    paths:
      - fig-files/file-spec/2024-data-points.json
      - fig-files/file-spec/json_to_csv.py
env:
  GIT_USERNAME: CFPBadmin
  GIT_EMAIL: CFPBadmin@users.noreply.github.com
  JSON_FILE_PATH: fig-files/file-spec/2024-data-points.json
  CSV_FILE_PATH: fig-files/file-spec/2024-data-points.csv
jobs:
  json-to-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python fig-files/file-spec/json_to_csv.py $JSON_FILE_PATH $CSV_FILE_PATH
      - name: View changes to CSV
        run: git diff $CSV_FILE_PATH
      - name: Push changes to CSV
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_EMAIL
          git commit -a -m "Update ${CSV_FILE_PATH} with changes from ${GITHUB_SHA::7}"
          git push
