version: "2.0"

services:
  mysql:
    image: vsamov/mysql-5.1.73
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cfpb
      MYSQL_DATABASE: cfpb
      MYSQL_USER: cfpb
      MYSQL_PASSWORD: cfpb
    volumes:
      - ./:/host:ro
  postgres:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cfpb
      POSTGRES_USER: cfpb
      POSTGRES_PASSWORD: cfpb
    volumes:
      - ./:/host
  pgloader:
    image: dimitri/pgloader:ccl.latest
    volumes:
      - ./:/host:ro
    depends_on:
      - mysql
      - postgres
