ogr2ogr -f "GeoJSON" ./output/ak.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ak"
ogr2ogr -f "GeoJSON" ./output/al.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_al"
ogr2ogr -f "GeoJSON" ./output/ar.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ar"
ogr2ogr -f "GeoJSON" ./output/as.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_as"
ogr2ogr -f "GeoJSON" ./output/az.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_az"
ogr2ogr -f "GeoJSON" ./output/ca.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ca"
ogr2ogr -f "GeoJSON" ./output/co.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_co"
ogr2ogr -f "GeoJSON" ./output/ct.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ct"

ogr2ogr -f "GeoJSON" ./output/dc.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_dc"
ogr2ogr -f "GeoJSON" ./output/de.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_de"
ogr2ogr -f "GeoJSON" ./output/fl.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_fl"
ogr2ogr -f "GeoJSON" ./output/ga.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ga"
ogr2ogr -f "GeoJSON" ./output/gu.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_gu"
ogr2ogr -f "GeoJSON" ./output/hi.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_hi"
ogr2ogr -f "GeoJSON" ./output/ia.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ia"
ogr2ogr -f "GeoJSON" ./output/id.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_id"

ogr2ogr -f "GeoJSON" ./output/il.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_il"
ogr2ogr -f "GeoJSON" ./output/in.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_in"
ogr2ogr -f "GeoJSON" ./output/ks.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ks"
ogr2ogr -f "GeoJSON" ./output/ky.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ky"
ogr2ogr -f "GeoJSON" ./output/la.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_la"
ogr2ogr -f "GeoJSON" ./output/ma.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ma"
ogr2ogr -f "GeoJSON" ./output/md.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_md"
ogr2ogr -f "GeoJSON" ./output/me.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_me"

ogr2ogr -f "GeoJSON" ./output/mi.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_mi"
ogr2ogr -f "GeoJSON" ./output/mn.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_mn"
ogr2ogr -f "GeoJSON" ./output/mo.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_mo"
ogr2ogr -f "GeoJSON" ./output/mp.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_mp"
ogr2ogr -f "GeoJSON" ./output/ms.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ms"
ogr2ogr -f "GeoJSON" ./output/mt.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_mt"
ogr2ogr -f "GeoJSON" ./output/nc.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_nc"
ogr2ogr -f "GeoJSON" ./output/nd.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_nd"

ogr2ogr -f "GeoJSON" ./output/ne.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ne"
ogr2ogr -f "GeoJSON" ./output/nh.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_nh"
ogr2ogr -f "GeoJSON" ./output/nj.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_nj"
ogr2ogr -f "GeoJSON" ./output/nm.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_nm"
ogr2ogr -f "GeoJSON" ./output/nv.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_nv"
ogr2ogr -f "GeoJSON" ./output/ny.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ny"
ogr2ogr -f "GeoJSON" ./output/oh.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_oh"
ogr2ogr -f "GeoJSON" ./output/ok.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ok"

ogr2ogr -f "GeoJSON" ./output/or.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_or"
ogr2ogr -f "GeoJSON" ./output/pa.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_pa"
ogr2ogr -f "GeoJSON" ./output/pr.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_pr"
ogr2ogr -f "GeoJSON" ./output/ri.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ri"
ogr2ogr -f "GeoJSON" ./output/sc.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_sc"
ogr2ogr -f "GeoJSON" ./output/sd.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_sd"
ogr2ogr -f "GeoJSON" ./output/tn.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_tn"
ogr2ogr -f "GeoJSON" ./output/tx.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_tx"

ogr2ogr -f "GeoJSON" ./output/ut.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_ut"
ogr2ogr -f "GeoJSON" ./output/va.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_va"
ogr2ogr -f "GeoJSON" ./output/vi.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_vi"
ogr2ogr -f "GeoJSON" ./output/vt.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_vt"
ogr2ogr -f "GeoJSON" ./output/wa.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_wa"
ogr2ogr -f "GeoJSON" ./output/wi.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_wi"
ogr2ogr -f "GeoJSON" ./output/wv.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_wv"
ogr2ogr -f "GeoJSON" ./output/wy.geojson PG:"host=localhost user=feomike dbname=feomike port=5432" -sql "select * from analysis.uauc_wy"
