apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-filter-configmap
data:
  bank-filter-list: "BANK1LEIFORTEST12345,BANK3LEIFORTEST12345,BANK4LEIFORTEST12345,999999LE3ZOZXUS7W648,28133080042813308004,B90YWS6AFX2LGWOXJ1LD"