{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "regtech-frontend.fullname" . }}
data:
  {{- tpl (toYaml .Values.configmap.data) . | nindent 2 }}
{{- end }}
