{{- if .Values.mapping.enabled -}}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "regtech-frontend.fullname" . }}
  labels:                                                                                                      
    {{- include "regtech-frontend.labels" . | nindent 4 }}
spec:
  ambassador_id:
    {{- toYaml .Values.mapping.ambassador_id | nindent 4 }}
  host: {{ tpl .Values.mapping.host . }}
  prefix: {{ .Values.mapping.prefix }}
  service: {{ include "regtech-frontend.fullname" . }}
{{- end }}
