---
r_shiny_pro: False
shiny_http_headers: "X-EXAMPLE"
shiny_required_users: "admin"
shiny_required_groups: "{{ restricted_group_name }}"
shiny_auth_proxy: False
shiny_auth_proxy_header: ""
shiny_admin_port: 4151
shiny_groups: ""
