# Default values for check-digit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hmda/census-api
  tag: grpc
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9093
  targetPort: 9093
  name: http-census

grpc:
  type: ClusterIP
  port: 60081
  targetPort: 60081
  name: http2-census

ingress:
  enabled: false
  annotations: {}
  ContainerPort: 9093
  hosts:
    - census-api.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: "2200Mi"
    cpu: "2"
  requests:
    memory: "2200Mi"
    cpu: "1"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
