{{- if .Values.secretProvider.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
spec:
  provider: {{ .Values.secretProvider.provider }}
  secretObjects:
    {{- toYaml .Values.secretProvider.secretObjects | nindent 4 }}
  parameters:
    {{- toYaml .Values.secretProvider.parameters | nindent 4 }}
{{- end }}