---
# tasks file for php

- name: install php
  yum: name=php state=present
  sudo: yes

- name: Copy php script
  template:
    src=info.php.j2
    dest=/var/www/info.php
  sudo: yes
  notify:
    - restart apache
    
    
