name: Python CI workflow

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Add the appropriate Tox environments for the satellite here
        toxenv:
            - py36-dj22
            - py38-dj22
        include:
          # Adjust the Python versions required for the tox environments as 
          # needed
          - toxenv: py36-dj22
            python-version: 3.6
          - toxenv: py38-dj22
            python-version: 3.8

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run back-end tests
        run: |
          tox
        env: 
          TOXENV: ${{ matrix.toxenv }}
