---
# Provisions the CKAN VM from scratch

- hosts: db
  gather_facts: False
  roles:
    - postgres
    - postgres-ckan

- hosts: search
  gather_facts: False
  roles:
    - solr

- hosts: local
  gather_facts: False
  roles:
    - iptables

- hosts: app
  gather_facts: False
  roles:
    - python27
    - apache
    - ckan
    - ace
