apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: regtech
  labels:
    mailing.app: mailpit
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8025
      protocol: TCP
      name: http
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smpt-port
  selector:
    mailing.app: mailpit
