apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kedro-etl-pipeline
bases:
resources:
- kedro-dev-env-configmap.yaml
- kedro-dev-postgres-configmap.yaml
- kedro-etl-pipeline-job-panel-2023.yaml
