language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-cfpb' ]; then cd .. && eval "mv $currentfolder generator-node-cfpb" && cd generator-node-cfpb; fi

