env:
 - MARATHONVERSION: 1.4.11
 - MARATHONVERSION: 1.3.0
 - MARATHONVERSION: 1.1.2
 - MARATHONVERSION: 0.15.3
 - MARATHONVERSION: 0.14.1
 - MARATHONVERSION: 0.13.1
 - MARATHONVERSION: 0.11.1
 - MARATHONVERSION: 0.10.1

language: python
python:
  - 2.7
install:
  - pip install tox
script:
  - make test
  - ./itests/install-marathon.sh
  - ./itests/start-marathon.sh &
  - make itests

# Work around travis-ci/travis-ci#5227
addons:
  hostname: localhost
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6-4.7-dev

sudo: required

deploy:
  - provider: pypi
    user: yelplabs
    password:
      secure: "Wl8GWxsfPy4KoORYH26N3FllvMeWrifzeCbEx2Af4corcBQl43heeiFRRTlUOcSX0TIasER21PUvQ0R0cAgCjfknDb3SOROcRtcSBe16+cMmvwysfxcAx2OcF1UYBPY8e/qOsGge2Zyzx2PAPNEmJoWKbIT3vUJ4WvlLVeGYdJ0="
    on:
      tags: true
      condition: $MARATHONVERSION == "1.4.7"
      repo: thefactory/marathon-python
