{{- if .Values.mapping.enabled -}}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "regtech-api.fullname" . }}
spec:
  ambassador_id:
    {{- toYaml .Values.mapping.ambassador_id | nindent 4 }}
  host: {{ tpl .Values.mapping.host . }}
  prefix: {{ .Values.mapping.prefix }}
  service: {{ include "regtech-api.fullname" . }}
  rewrite: {{ .Values.mapping.rewrite }}
  timeout_ms: {{ .Values.mapping.timeout_ms }}
{{- end }}