---
- hosts: elasticsearch
  become: yes
  become_method: sudo
  roles:
    - elasticsearch-config

- hosts: elk
  become: yes
  become_method: sudo
  roles:
    - elasticsearch-config
    - logstash-config
    - kibana-config
