---
- hosts: analytics_terminal
  become: yes
  become_method: sudo
  roles:
    - r-core
    - r-libs
    - r-shiny
    - r-shiny-config
    - r-studio-server
    - r-studio-server-config
    - r-studio-desktop
