name: Publish docs
on: 
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --no-tags --prune --depth=1 origin gh-pages

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ."[docs]"

      - name: Build docs
        run: mkdocs build

      - name: Publish docs
        run: mkdocs gh-deploy
