sudo: required
language: python
cache: pip
python:
- 2.7
nodejs: 6
services:
- mysql
before_install:
- npm install -g npm
- ./.travis-install-mysql-5.7.sh
- mysql -uroot -e "CREATE USER 'eregs'@'localhost' IDENTIFIED BY 'eregs';"
- mysql -uroot -e "GRANT ALL PRIVILEGES ON \`test_%\`.* TO 'eregs'@'localhost';"
install: pip install tox coveralls
before_script:
- ./setup.sh
script:
- npm test
- TOXENV=dj18 tox
- python2.7 setup.py bdist_wheel
after_success: coveralls
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UQZ16cdJ48IHL4Ve4oZ9zkKQqRAeDi9wMPb5RJGM3FnoVAONV5lHQTKdH2FulfRvXBa5JK1x5fcjivaKczS0uIDbcyKiKWiMI44xyFl22FLnpq6OWX55TFe8YpF+UFHcB63bej4Nxsicnug/zkW26xS9ZrwMRgz+xjoIDZRmEi5NdDtwIsqClpfFfLm3Kdhs7plYlXi1K2GLUcJY3UVfwvFd6EQhsuAMtwvZ56AaOQiYBCjWTTzXUaYK/ythYMZBIm/rDCDLsItFzdGyIv3IfFyJPzwmITWupJ90FbXiaXqF3eMtbHZa54JMmVkU3smnSgdqvQFDNfOoz+WEdX47IhmNQV5L7QaN0uSXcBmxl6J2ud/bh4024hk60Cey4KPdEv7h8fKPTwe4Uer70b3h6OoL4fmGJM0ny6y6ka0zS1Hq2A/oSJ1bUbmiucFNL1eggCqknFdo45Mc/AVTtDf1wUahUGF07LV+PwaFz5BTPfaIzxJVplJQAQrR8EivWkymLKtPmVduvb11GPLnphdPMvzCqVH+3Gqh0ApH6nhD/AyHij/t1Wj/BcPHtz2FPxkXcHSvTyX49GelXBz9kutBaea+QcCmFZR3YVxZHHtvKDY4IgNLedXjHYVBcKEIOvwYy81rCP+pzImhijeu4TnaHF1DjC2HWMia7kowJiadqi4=
  file_glob: true
  file: dist/*.whl
  on:
    tags: true
