{{- if .Values.runJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kedro-data-publisher.releaseName" $ }}-{{ $.Values.jobName }}-{{ $.Values.year | toString | replace "_" "-"}}
  labels:
    job: {{- include "kedro-data-publisher.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: kedro
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kedro-aws-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kedro-aws-credentials
                  key: aws-secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: CURRENT_YEAR
              value: "{{ $.Values.year }}_Filing_Season"
            - name: TO_OUTPUTS
              value: "{{ $.Values.output }}_{{ $.Values.year }}"
            - name: KEDRO_DEV
              value: dev
            - name: SQLALCHEMY_SILENCE_UBER_WARNING
              value: "1"
          volumeMounts:
            - name: kedro-base-credentials
              readOnly: true
              mountPath: /tmp/kedro-base-credentials
            - name: kedro-dev-credentials
              readOnly: true
              mountPath: /tmp/kedro-dev-credentials
            - name: kedro-dev-env-configmap
              readOnly: true
              mountPath: /tmp/kedro-dev-env-configmap
          command:
            - /bin/bash
            - "-c"
            - date; cp /tmp/kedro-base-credentials/credentials.yaml  /hmda-etl-pipeline/conf/base/credentials.yaml; cp /tmp/kedro-dev-credentials/credentials.yaml /hmda-etl-pipeline/conf/dev/credentials.yaml; cp /tmp/kedro-dev-env-configmap/globals.yml  /hmda-etl-pipeline/conf/dev/globals.yml; mkdir -p /hmda-etl-pipeline/logs && touch /hmda-etl-pipeline/logs/info.log ; cd /hmda-etl-pipeline/; kedro run --tags="$(CURRENT_YEAR)" --env=$(KEDRO_DEV) --pipeline={{ $.Values.pipeline }} --runner=ThreadRunner --params=max_workers=6,post_to_mm={{ $.Values.post_to_mm }},post_to_mm_verbose={{ $.Values.post_to_mm_verbose }} --to-outputs=${TO_OUTPUTS}
      volumes:
        - name: kedro-base-credentials
          secret:
            secretName: kedro-base-credentials
        - name: kedro-dev-credentials
          secret:
            secretName: kedro-dev-credentials
        - name: kedro-dev-env-configmap
          configMap:
            name: kedro-dev-env-configmap
      tolerations:
        - key: node-group
          operator: Equal
          value: {{ $.Values.nodeGroup }}
      restartPolicy: OnFailure
{{- end }}