version: 2
jobs:
  build:
    working_directory: ~/wagtail-autocomplete-repo
    docker:
      - image: randomknowledge/docker-pyenv-tox
    steps:
      - checkout
      - run:
          name: tests
          command: tox
      - run:
          name: flake8
          command: tox -e flake8
