language: java
sudo: false

before_install:
  # Remove outdated settings.xml from Travis builds. Workaround for https://github.com/travis-ci/travis-ci/issues/4629
  - rm ~/.m2/settings.xml

install: "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"

script: mvn test
