source_filepath: "../edits_files/clean_files/Bank1/" 
source_filename: "clean_file_100_rows_Bank1.txt"
output_filepath: "../edits_files/large_test_files/" 
output_filename: "large_file_10000_rows.txt"
row_by_row_modification_yaml_file:
bank_name: "Bank1"
lei: BANK1LEIFORTEST12345
tax_id: 02-1234567
row_count: 10000