site_name: Owning-a-home API
pages:
- Introduction: index.md
- Usage:
    - API endpoints: api.md

theme: mkDOCter
extra:
    brand_color: "#2CB34A"
    logo_url: https://cfpb.github.io/img/logo_210.png
    logo_alt: Consumer Financial Protection Bureau

markdown_extensions:
    - admonition
    - tables
