apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "friendly-umbrella.fullname" . }}
  labels:
    {{- include "friendly-umbrella.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "friendly-umbrella.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "friendly-umbrella.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "friendly-umbrella.serviceAccountName" . }}
      {{- with .Values.specSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- range .Values.initContainers }}
      - name: {{ .name }}
        image: "{{.image.repository}}:{{ .image.tag}}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .port }}
          protocol: TCP
        {{- if .command }}
        command:
          {{- range .command }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
        {{ if .args }}
        args:
          {{- range .args }}
          - "{{ . }}"
          {{- end }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ $.Release.Name }}-configmap
        {{ if .env}}
        env:
          {{- range .env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
      {{- range .Values.containers }}
      - name: {{ .name }}
        image: "{{.image.repository}}:{{ .image.tag}}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .port }}
          protocol: TCP
        {{- if .command }}
        command:
          {{- range .command }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
        {{ if .args }}
        args:
          {{- range .args }}
          - "{{ . }}"
          {{- end }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ $.Release.Name }}-configmap
        {{ if .env}}
        env:
          {{- range .env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
