{{- if .Values.mapping.enabled }}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "friendly-umbrella.fullname" . }}
  labels:
    {{- include "friendly-umbrella.labels" . | nindent 4 }}
spec:
  ambassador_id:
    {{- toYaml .Values.mapping.ambassador_id | nindent 4 }}
  host: {{ .Values.mapping.host }}
  prefix: {{ .Values.mapping.prefix | default "/" }}
  service: {{ include "friendly-umbrella.fullname" . }}:{{ .Values.service.port }}
  timeout_ms: 0
{{- end }}