apiVersion: v1
kind: Service
metadata:
  name: {{ include "friendly-umbrella.fullname" . }}
  labels:
    {{- include "friendly-umbrella.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "friendly-umbrella.selectorLabels" . | nindent 4 }}
