kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{.Values.service.account.name}}
    namespace: hmda-kind
roleRef:
  kind: ClusterRole
  name: pod-reader-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io