apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap
data:
  cassandra-hosts: cluster1-dc1-service.cass-operator
  cassandra-keyspace: hmda2_journal
  cassandra-keyspace-snapshot: hmda2_snapshot