apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  postgres.ssl: require
  postgres.user:  hmda
  postgres.database: hmda

