enabled: false
ambassador_id: "--apiVersion-v3alpha1-only--default"
target_namespace: ""
mappings: []
#  - host: foo
#    service: foo
#  - host: bar
#    prefix: /
#    service: bar
#    rewrite: /
#    port: 8080
