sidecar:
  dashboards:
    enabled: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    cfgov-performance-metrics:
      file: dashboards/cfgov-metrics.json

plugins:
  - grafana-newrelic-datasource
