---
- name: Install postgres repository
  yum:
    name: "{{ postgres_repository_url }}"
    state: present
  when: postgres_install_repository
  tags:
    - postgres_client

- name: Install postgres repository key
  rpm_key:
    key: "{{ postgres_repository_key_url }}"
    state: present
  when: postgres_install_repository
  tags:
    - postgres_client

- name: Ensure older versions are removed
  yum:
    name: "{{ item }}"
    state: absent
    disablerepo: "{{ postgres_repository_name }}"
  ignore_errors: yes
  with_items: "{{ postgres_old_packages }}"
  when: clean_postgresql
  tags:
    - postgres_client

- name: Install postgres packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgres_packages }}"
  tags:
    - postgres_client

- name: Install gis postgres packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgres_gis_packages }}"
  ignore_errors: True
  tags:
    - postgres_client

- name: Ensure other libraries can see header files
  file:
    src: "{{ postgres_install_dir }}/include/"
    dest: /usr/include/pgsql
    state: link
  tags:
    - postgres_client

- name: Ensure other libraries can see library files
  file:
    src: "{{ postgres_install_dir }}/lib"
    dest: /usr/lib/pgsql
    state: link
  tags:
    - postgres_client

- name: Add psql bin directory to path
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  tags:
    - postgres_client

- name: Create a symlink that can remain constant during upgrades
  file:
    src: "{{ postgres_install_dir }}"
    dest: /usr/pgsql
    state: link
  tags:
    - postgres_client
