# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: pygments

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: CFPB Hack Day
subtitle: Thursday, April 14

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/hackathon'

# Author/Organization info to be displayed in the templates
author:
  name: CFPB
  url: http://cfpb.github.io/hackathon

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /hackathon/assets/img/logo_210.png
logoalt: CFPB

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Schedule
  url: ./schedule
  internal: true
- text: Projects
  url: ./projects
  internal: true
- text: Code of Conduct
  url: ./code-of-conduct
  internal: true


# Style Variables
brand_color: "#2cb34a"
