---
# tasks file for postgres-ckan
- name: create postgres db
  postgresql_db:
    name={{ckan_db_name}}
    encoding='UTF-8'
    login_host={{postgres_login_host}}
    login_user={{postgres_login_user}}
    login_password={{postgres_login_password}}
    port={{postgres_port}}
  sudo: yes
  register: create_ckan_db
  sudo_user: postgres

- name: create ckan db user
  postgresql_user: 
    db="{{ckan_db_name}}" 
    name="{{ckan_db_user}}" 
    password="{{ckan_db_password}}"
    #priv="ALL"
  sudo: yes
  register: create_ckan_db_user
  sudo_user: postgres

- name: create ckan datastore db
  postgresql_db:
    name={{ckan_datastore_db_name}}
    encoding='UTF-8'
    owner="{{ckan_db_user}}"
    login_host={{postgres_login_host}}
    login_user={{postgres_login_user}}
    login_password={{postgres_login_password}}
    port={{postgres_port}}
  sudo: yes
  register: create_datastore_db
  sudo_user: postgres

- name: create datastore db user
  postgresql_user: 
    db="{{ckan_datastore_db_name}}" 
    name="{{ckan_datastore_db_user}}" 
    password="{{ckan_datastore_db_password}}"
    #priv="ALL"
  sudo: yes
  register: create_datastore_db_user
  sudo_user: postgres


