dist: trusty # for python 2.6 support
language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"

before_script: "mv collab/local_settings_template.py collab/local_settings.py"
script: "python manage.py test"
