name: Deploy CF.gov to EKS
on: 
  push:
  workflow_call:
jobs: 
  build: 
    runs-on: 
      - codebuild-cfpb-cfgov-actions-gha-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: my-step
        run: echo "Hello World!"
