# production compose
# extend from docker-compose-common.yml
geocoder:
  extends:
    file: docker-compose-common.yml
    service: geocoder
  links:
    - parser
    - elasticsearch
    - influxdb
  environment: &MONITORED_JVM_ENV
    IS_MONITORED: 'true'
    INFLUXDB_HOST: &INFLUXDB_HOST influxdb
    INFLUXDB_PORT: &INFLUXDB_PORT 8086
    INFLUXDB_USER: &INFLUXDB_USER root
    INFLUXDB_PASSWORD: &INFLUXDB_PASSWORD root

parser:
  extends:
    file: docker-compose-common.yml
    service: parser

loader:
  extends:
    file: docker-compose-common.yml
    service: loader
  links:
    - elasticsearch

elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch

ui:
  extends:
    file: docker-compose-common.yml
    service: ui
  links:
    - geocoder

# services that are not extended
cadvisor:
  image: google/cadvisor:0.16.0
  ports:
    - "9090:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxdb
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086

influxdb:
  image: tutum/influxdb:0.8.8
  ports:
    - 8083:8083 # Admin Site
    - 8086:8086 # API
  environment:
    # Extra auto-create magic provided by this image
    PRE_CREATE_DB: "cadvisor;metrics"

grafana:
  build: docker/grafana
  ports:
    - 3000:3000
  links:
    - influxdb

# Logspout setup taken from:
#   https://github.com/gliderlabs/logspout#route-all-container-output-to-remote-syslog
logspout:
  image: gliderlabs/logspout:master
  ports:
    - "8000:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  links:
    - logstash
  environment:
    LOGSPOUT: ignore
    # Logstash only supports the older RFC 3164 syslog protocol
    SYSLOG_FORMAT: rfc3164
  # Use syslog+tcp:// if UDP is not supported
  command: syslog://logstash:5514

logstash:
  build: docker/logstash
  expose:
    - 5514
  links:
    - elasticsearch
  environment:
    LOGSPOUT: ignore
  command: logstash --verbose -f /opt/grasshopper.conf -e 'input{ syslog{ port => 5514 } } output{ elasticsearch{ protocol => "http" host => "elasticsearch" } }'

kibana:
  build: docker/kibana
  environment:
    LOGSPOUT: ignore
  links:
    - elasticsearch
  ports:
    - "5601:5601"

