apiVersion: v1
kind: Service
metadata:
  name: ambassador-hmda-reporting-beta
  namespace: beta
  labels:
    app.kubernetes.io/managed-by: Helm
    service: ambassador-hmda-reporting
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind: Mapping
      name: hmda_reporting_mapping_beta
      ambassador_id: ambassador-beta-2
      prefix: /v2/reporting/
      service: hmda-reporting.default.svc.cluster.local:9094
      timeout_ms: 180000
      retry_policy:
        num_retries: 10
        retry_on: 5xx
      add_response_headers:
        referrer-policy: 
          value: strict-origin
          append: False
        content-security-policy: 
          append: False
          value: "default-src 'self'; script-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; object-src 'none'; frame-src 'self'; connect-src 'self'"
        permissions-policy:
          value: "autoplay=(), encrypted-media=(), fullscreen=(), geolocation=(), microphone=(), midi=()"
        x-frame-Options: 
          value : "SAMEORIGIN"
        x-content-type-options: 
          value : nosniff
        strict-transport-security:
          value: "max-age=31536000; includeSubDomains; preload"
        x-xss-protection:
          value: "1; mode=block"
      remove_response_headers:
      - Access-Control-Allow-Origin
      - x-envoy-upstream-service-time
      - x-forwarded-host
      - x-host
      - x-forwarded-server
spec:
  clusterIP: None
