language: python

script:
  - git clone https://github.com/cfpb/regulations-xml-parser.git
  - git clone https://github.com/cfpb/regulations-schema.git
  - pip install -r regulations-xml-parser/requirements.txt
  - echo "XSD_FILE = 'regulations-schema/src/eregs.xsd'" >> regulations-xml-parser/local_settings.py
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE"
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - export GIT_COMMITS="$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo ${TRAVIS_COMMIT_RANGE:-HEAD~1 HEAD}; else echo $TRAVIS_BRANCH; fi)"
  - REGML_PY=regulations-xml-parser/regml.py ./validate_xml.sh
