# These are datasets that come from our production postgres database.

# LAR count by LEI is included within this file, but it may make more sense for this
# dataset to exist within the initial_could_validation.yaml file. 

# This file is the same for all years before 2024
pg_cbsa_county_name_{year}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM hmda_user.cbsa_county_name;"
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

pg_lar_{year}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM hmda_user.loanapplicationregister{year};"
  load_args:
    chunksize: 250000
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

# The institutions email table is a single table used for all years. Appending
# the year to the end of the Kedro dataset name for consistency
pg_institutions_email_domains_{year}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM institutions_emails_2018;"
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

# This dataset is cached because it is used twice. Once to verify the row counts
# and a second time to calculate the number of partitions in the raw LAR dataset
pg_lar_counts_by_lei_{year}:
  type: CachedDataset
  dataset:
    type: pandas.SQLQueryDataset
    sql: "SELECT lei, COUNT(*) FROM hmda_user.loanapplicationregister{year} GROUP BY lei;"
    credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

pg_institutions_{year}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM hmda_user.institutions{year};"
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

pg_ts_{year}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM hmda_user.transmittalsheet{year};"
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

pg_lar_{year}_{quarter}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM hmda_user.lar{year}_{quarter};"
  load_args:
    chunksize: 250000
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

pg_lar_counts_by_lei_{year}_{quarter}:
  type: CachedDataset
  dataset:
    type: pandas.SQLQueryDataset
    sql: "SELECT lei, COUNT(*) FROM hmda_user.lar{year}_{quarter} GROUP BY lei;"
    credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres

pg_ts_{year}_{quarter}:
  type: pandas.SQLQueryDataset
  sql: "SELECT * FROM hmda_user.ts{year}_{quarter};"
  credentials: production_pg_readonly
  metadata:
    kedro-viz:
      layer: Production Postgres
